# Generated by Django 5.2 on 2025-05-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_prompt',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
